swagger: "2.0"
info:
  title: Weather Service
  description: This API description describes all endpoints existing for the weather service. This includes all endpoints required for the frontend.
  version: 1.0.0.0
host: api.livius.io
schemes:
  - https
paths:
  /api/v1/weather/all:
    get:
      summary: Return all weather events.
      description: Returns a pageable list of all weather events.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /api/v1/weather/{id}:
    get:
      summary: Return a single weather event.
      description: Returns a single weather event when one exists with the specified id.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /api/v1/weather/search:
    get:
      summary: Returns a list of weather events.
      description: Returns a pageable list of weather events that fit the search criteria.
      produces:
        - application/json
      responses:
        200:
          description: OK