openapi: "3.0.2"
info:
  title: Livius - Weather API
  description: The main api for handling weather data and the access to it.
  version: "1.0.0.0"
servers:
  - url: https://livius.io
    description: Public api, can be used for testing or general use. There are some limiters in place to prevent abuse.
  - url: http://localhost:4000
    description: API hosted through the localhost. This should be provided by you.
paths:
  /api/v1/weather/all:
    get:
      summary: Return a list containing weather data.
      description: The list that is returned here contains a pageable selection of weather data.
      responses:
        '200':
          description: A List of weather data.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weather'
  /api/v1/weather/{id}:
    get:
      summary: Returns a single weather event.
      description: Returns a single weather event based on the provided id.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id of a weather event.
      responses:
        '200':
          description: A List of weather data.
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Weather'
  /api/v1/weather/station/all:
    get:
      summary: Returns a list of stations.
      description: Returns a list of all stations that are known to the livius instance.
      responses:
        '200':
          description: A list of weather stations.
          content:
            application/json:
              schema:
                type: array
  /api/v1/weather/station/count/{station}:
    get:
      summary: Counts weather data for station.
      description: Returns the count of weather events attributed to the specified station.
      parameters:
        - in: path
          name: station
          schema:
            type: string
          required: true
          description: Weather station ID.
      responses:
        '400':
          description: If the provided station does not exist.
        '200':
          description: Count of weather events.
          content:
            application/json:
              schema:
                type: number
                example: 5000
components:
  schemas:
    Weather:
      description: This object represents weather data at a specific point in time.
      properties:
        id:
          type: string
        station:
          type: string
        date:
          type: string
        source:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        elevation:
          type: number
        name:
          type: string
        report_type:
          type: string
        call_sign:
          type: string
        quality_control:
          type: string
        wind:
          type: string
        cig:
          type: number
        temperature:
          type: string
        dew:
          type: string
        slp:
          type: string
        citation:
          type: string
        accessDate:
          type: string
        created:
          type: object
        updated:
          type: object
        dataset_url:
          type: string