site_name: Livius Documentation
site_url: https://docs.livius.io
copyright: Copyright &copy; 2021 - 2024 Ben Coepp Publishing
repo_url: https://github.com/bencoepp/livius
repo_name: bencoepp/livius
plugins:
  - tags
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - offline
theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.footer
  palette:
    scheme: slate
    primary: green
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true