apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: livius
data:
  config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      replication_factor: 1
      path_prefix: /tmp/loki
    schema_config:
      configs:
        - from: 2020-05-15
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      filesystem:
        directory: /tmp/loki/chunks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: livius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livius
      tier: loki
  template:
    metadata:
      labels:
        app: livius
        tier: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:main
          ports:
            - containerPort: 3100
          args:
            - "-config.file=/etc/loki/config.yaml"
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: livius
  labels:
    app: livius
    tier: loki
spec:
  clusterIP: None
  ports:
    - port: 3100
      name: loki-svc
  selector:
    app: livius
    tier: loki