apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: livius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livius
      tier: tempo
  template:
    metadata:
      labels:
        app: livius
        tier: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          ports:
            - containerPort: 3100
              name: tempo
            - containerPort: 9411
              name: zipkin
          args:
            - "-config.file=/etc/tempo/config.yaml"
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: livius
  labels:
    app: livius
    tier: tempo
spec:
  clusterIP: None
  ports:
    - port: 3100
      name: tempo-svc
  selector:
    app: livius
    tier: tempo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: livius
data:
  config.yaml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        zipkin:
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks