apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  namespace: livius
  labels:
    app: livius
    tier: data
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: livius
      tier: data
  template:
    metadata:
      labels:
        app: livius
        tier: data
    spec:
      containers:
        - name: data-service
          image: registry.bencoepp.de/livius/data:1.0.0.3
          ports:
            - containerPort: 3000
          env:
            - name: EUREKA_LIVIUS
              value: http://eureka-0.eureka.livius.svc.cluster.local:8761/eureka
            - name: LIVIUS_DB_URI
              value: mongodb://root:example@mongodb.livius.svc.cluster.local:27017
            - name: LIVIUS_DB
              value: test
            - name: LIVIUS_APP_COW_START_JOBS
              value: true
            - name: LIVIUS_APP_WEATHER_START_JOBS
              value: true
---
apiVersion: v1
kind: Service
metadata:
  name: data
  namespace: livius
  labels:
    app: livius
    tier: data
spec:
  clusterIP: None
  ports:
    - port: 3000
      name: data-svc
  selector:
    app: livius
    tier: data