apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: livius
  labels:
    app: livius
    tier: weather
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: livius
      tier: weather
  template:
    metadata:
      labels:
        app: livius
        tier: weather
    spec:
      containers:
        - name: weather-service
          image: registry.bencoepp.de/livius/weather:1.0.0.0
          ports:
            - containerPort: 4000