apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  namespace: livius
  labels:
    app: livius
    tier: data
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: livius
      tier: data
  template:
    metadata:
      labels:
        app: livius
        tier: data
    spec:
      containers:
        - name: data-service
          image: registry.bencoepp.de/livius/data:1.0.0.0
          ports:
            - containerPort: 3000