apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: livius
  labels:
    app: livius
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: livius
      tier: frontend
  template:
    metadata:
      labels:
        app: livius
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: registry.bencoepp.de/livius/frontend:latest
          ports:
            - containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
  namespace: livius
spec:
  selector:
    app: livius
    tier: frontend
  ports:
    - port:  8000
      targetPort:  8000
      nodePort: 30090
  type: NodePort