apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  namespace: livius
data:
  eureka_service_address: http://eureka-0.eureka:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: livius
  labels:
    app: livius
    tier: eureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka-svc
  selector:
    app: livius
    tier: eureka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: livius
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: livius
      tier: eureka
  template:
    metadata:
      labels:
        app: livius
        tier: eureka
    spec:
      containers:
        - name: eureka
          image: registry.bencoepp.de/livius/eureka:1.0.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: LIVIUS_LOKI_URI
              value: loki.livius.svc.cluster.local
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address