server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SIFF:http://localhost:8761/eureka}