package bencoepp.livius.entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Represents an autogenerated identifier for MongoDB entities.
 * This class is used to handle the sequence generation for entity IDs in a MongoDB collection.
 */
@Document(collection = "db_sequence")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AutogenerateId {
    /**
     * The unique identifier for the sequence entity.
     * This field is annotated as the ID field in MongoDB.
     */
    @Id
    private String id;
    /**
     * The sequence number associated with this ID.
     * This can be used to generate unique IDs for other entities.
     */
    private String seq;
}
