name: Build & Release Eureka

on: [push, pull_request]

env:
  REGISTRY: registry.bencoepp.de
  IMAGE_NAME: ${{ github.repository }}/eureka


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - run: mvn -f ./backend/pom.xml test
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ./backend
        run: docker build . --file Dockerfile --build-arg PATH=services/eureka --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Push Image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}