name: Build and deliver backend services

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and deliver backend services
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - run: mvn -f ./backend/pom.xml package