name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there, and welcome to the livius project. We thank you for bringing your issue to our attention. Please feel free to browse around and see if there is anything else you might add to the issue so thast we know how to help you."
        pr-message: "Thank you very much for your PR. We will get back to you shortly. Please note that depending on what files you have edited the review and audit can take a few minutes."
